project:
  type: website
  output-dir: docs
  resources:
    - files/**

#   
# execute: 
#   warning: FALSE
#   message: FALSE
#   cache: true
# 
# comments:
#   hypothesis: 
#     theme: clean

pagetitle: "{{< meta title >}} | Jeff Baldock"
author-meta: "Jeff Baldock"

website:
  title: "Jeff Baldock"
  site-url: "https://j-baldock.github.io/"
  navbar:
    left: 
      # - text: "Home"
      #   href: index.qmd
      - text: "About"
        href: about/about.qmd
      - text: "Research"
        href: research/research.qmd
      - text: "Publications"
        href: publications/publications.qmd
      - text: "Outreach"
        menu: 
          - text: "Presentations"
            href: presentations/presentations.qmd
          - text: "Teaching and mentoring"
            href: teaching/teaching.qmd
          - text: "Events"
            href: events/events.qmd
      - text: "Open science & data"
        href: dataprod/dataproducts.qmd
    right:
      - text: "CV"
        href: cv/cv.qmd
      - icon: github
        href: https://github.com/j-baldock
        target: _blank
      - text: "{{< ai google-scholar size=Large >}}"
        href: https://scholar-google-com.usgslibrary.idm.oclc.org/citations?user=CRU3WVMAAAAJ&hl=en
        target: _blank
      - text: "{{< ai researchgate size=Large >}}"
        href: https://www.researchgate.net/profile/Jeff-Baldock
        target: _blank
      - text: "{{< ai orcid size=large >}}"
        href: https://orcid.org/0000-0002-2791-7535
        target: _blank

  page-footer:  
    left: >-
     &#169; 2025 Jeff Baldock &#8729; Made with [Quarto](https://quarto.org)


format:
  html:
    theme: flatly
    number-depth: 4
      

editor: source